@startuml
'https://plantuml.com/class-diagram
!theme _none_
Person *--"0..*" Mitarbeiter : ist <
Person *--"0..*" Kunden : ist <

Mitarbeiter "1"--"0..*" Beratung : betreut >
Mitarbeiter "1"--"0..*" Mietvertrag : schließt >

Kunden "1"--"1..*" Beratung : beansprucht >

KfzTyp o--"0..*" Kfz : zugehörig <
Sonderausstattung "0..*"--"0..*" Kfz : verbaut in >

Beratung "1"--"1" Reservierung : führt zu >

Reservierung *--"1" Mietvertrag : resultiert aus <

Rechnung "1"--o Mietvertrag : erzeugt <
Rechnung "0...*"--"1" Kunden : tilgt <

Kfz "1"--"0..*" Reservierung : reserviert <
Zubehör "0..*"--"0..*" Reservierung : reserviert <

Zubehör "0..*"--"0..*" Beratung : empfiehlt <
KfzTyp "1..*"--"0..*" Beratung : empfiehlt <

Sonderausstattung "0..*"--"0--*" Beratung : empfiehlt <


abstract class Person {
Titel: String
Vorname: String
Nachname: String
Straße: String
Hausnummer: Int
Ort: String
PLZ: Number
Land: String
BIC: String
IBAN: String
Telefonnummer: Number
}

class Mitarbeiter {
Personalnummer: Number
Position: String

berät(): Beratung
}

class Kunden {
Kundennummer: Number
Stammkunde: Boolean

äußert_wünsche(): Beratung
tilgt_rechnung()
}

class Beratung {
Kundennummer: Number
Personalnummer: Number
WunschTyp: KfzTyp[]
WunschAusstattung: Sonderausstattung[]
WunschZubehör: Zubehör[]
Datum: Date

erstelle_reservierung(): Reservierung
}

class KfzTyp {
Bezeichnung: String
}

class Sonderausstattung{
Bezeichnung: String
}

class Kfz {
Karosserienummer: Number
Nummernschild: String
Modell: Number
Preis: Float
FahrzeugKlasse: KfzTyp
Verbaut: Sonderausstattung[]
}

class Zubehör{
Bezeichnung: String
Preis: Float
}

class Reservierung {
reservierungsnummer
kundennummer: Number
Fahrzeug: Kfz
Zubehör: Zubehör[]
datumVon: Date
datumBis: Date
Datum: Date

erstelle_Vertrag(): Mietvertrag
}

class Mietvertrag {
kundennummer: Number
Mitarbeiter: Number
Rechnungsnummer: Number
Datum: Date

erstelle_rechnung(): Rechnung
}

class Rechnung {
Rechnungsnummer: Number
Kundennummer: Number
Rechnungsposition: Object[]
Datum: Date
Betrag: Float
Rabatt: Float
}

@enduml